## Cell 1 — Imports

In [19]:
# IMPORTS

import os
import random
import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from torch.utils.data import (
    Dataset,
    DataLoader,
    Subset,
    WeightedRandomSampler
)

from torchvision import transforms

import timm
from timm.utils import ModelEmaV2

from sklearn.metrics import (
    balanced_accuracy_score,
    confusion_matrix
)

from sklearn.model_selection import train_test_split

from tqdm import tqdm

## Cell 2 — Seed

In [20]:
# SEED

def seed_everything(seed=42):

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    os.environ["PYTHONHASHSEED"] = str(seed)

    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(42)

## Cell 3 — Device

In [21]:
# DEVICE

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("🔥 DEVICE:", device)

🔥 DEVICE: cuda


## Cell 4 — Classes

In [22]:
# CLASSES

classes = [
    "anger",
    "disgust",
    "fear",
    "happy",
    "neutral",
    "sad",
    "surprise"
]

label_map = {
    c:i for i,c in enumerate(classes)
}

num_classes = len(classes)

print(label_map)

{'anger': 0, 'disgust': 1, 'fear': 2, 'happy': 3, 'neutral': 4, 'sad': 5, 'surprise': 6}


## Cell 5 — Dataset Paths

In [23]:
# DATASET PATHS

BASE = (
    "/kaggle/input/datasets/"
    "sirguthemen/"
    "preprocessed-fed-datset-collection"
)

teacher_root = os.path.join(
    BASE,
    "preprocessed_teacher_224",
    "preprocessed_teacher_224"
)

student_root = os.path.join(
    BASE,
    "preprocessed_student_96",
    "preprocessed_student_96"
)

print("Teacher root:")
print(teacher_root)

print("\nStudent root:")
print(student_root)

print("\nTeacher datasets:")
print(os.listdir(teacher_root))

print("\nStudent datasets:")
print(os.listdir(student_root))

Teacher root:
/kaggle/input/datasets/sirguthemen/preprocessed-fed-datset-collection/preprocessed_teacher_224/preprocessed_teacher_224

Student root:
/kaggle/input/datasets/sirguthemen/preprocessed-fed-datset-collection/preprocessed_student_96/preprocessed_student_96

Teacher datasets:
['Custom', 'KDEF', 'AffectNet', 'FER2013', 'CKPLUS', 'RAF-DB', 'FacialEmotionRecognition']

Student datasets:
['Custom', 'KDEF', 'AffectNet', 'FER2013', 'CKPLUS', 'RAF-DB', 'FacialEmotionRecognition']


## Cell 6 — Transforms

In [24]:
# TRANSFORMS

train_teacher_tf = transforms.Compose([

    transforms.RandomResizedCrop(
        224,
        scale=(0.75, 1.0)
    ),

    transforms.RandomHorizontalFlip(),

    transforms.ColorJitter(
        brightness=0.25,
        contrast=0.25,
        saturation=0.25,
        hue=0.1
    ),

    transforms.RandomRotation(15),

    transforms.ToTensor(),

    transforms.RandomErasing(
        p=0.25
    ),

    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

train_student_tf = transforms.Compose([

    transforms.RandomResizedCrop(
        128,
        scale=(0.75, 1.0)
    ),

    transforms.RandomHorizontalFlip(),

    transforms.ColorJitter(
        brightness=0.25,
        contrast=0.25,
        saturation=0.25,
        hue=0.1
    ),

    transforms.RandomRotation(15),

    transforms.ToTensor(),

    transforms.RandomErasing(
        p=0.25
    ),

    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

val_teacher_tf = transforms.Compose([

    transforms.Resize((224,224)),

    transforms.ToTensor(),

    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

val_student_tf = transforms.Compose([

    transforms.Resize((128,128)),

    transforms.ToTensor(),

    transforms.Normalize(
        [0.485,0.456,0.406],
        [0.229,0.224,0.225]
    )
])

## Cell 7 — Dataset Class

In [25]:
# DATASET

class FERDataset(Dataset):

    def __init__(
        self,
        teacher_tf,
        student_tf
    ):

        self.teacher_tf = teacher_tf
        self.student_tf = student_tf

        self.samples = []

        dataset_names = os.listdir(
            teacher_root
        )

        for dataset_name in dataset_names:

            teacher_dataset = os.path.join(
                teacher_root,
                dataset_name
            )

            for emotion in classes:

                emo_folder = os.path.join(
                    teacher_dataset,
                    emotion
                )

                if not os.path.exists(
                    emo_folder
                ):
                    continue

                for fname in os.listdir(
                    emo_folder
                ):

                    if fname.lower().endswith(
                        (
                            ".jpg",
                            ".jpeg",
                            ".png"
                        )
                    ):

                        self.samples.append(
                            (
                                os.path.join(
                                    emo_folder,
                                    fname
                                ),

                                label_map[emotion]
                            )
                        )

        print(
            f"✅ TOTAL IMAGES: "
            f"{len(self.samples)}"
        )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        path, label = self.samples[idx]

        img = Image.open(
            path
        ).convert("RGB")

        t_img = self.teacher_tf(img)

        s_img = self.student_tf(img)

        return t_img, s_img, label

## Cell 8 — Dataset Split

In [26]:
# DATASET

full_dataset = FERDataset(
    train_teacher_tf,
    train_student_tf
)

labels = [
    s[1]
    for s in full_dataset.samples
]

indices = np.arange(len(labels))

train_idx, val_idx = train_test_split(

    indices,

    test_size=0.2,

    stratify=labels,

    random_state=42
)

train_ds = Subset(
    full_dataset,
    train_idx
)

val_full = FERDataset(
    val_teacher_tf,
    val_student_tf
)

val_ds = Subset(
    val_full,
    val_idx
)

print("Train size:", len(train_ds))
print("Validation size:", len(val_ds))

✅ TOTAL IMAGES: 42342
✅ TOTAL IMAGES: 42342
Train size: 33873
Validation size: 8469


## Cell 9 — Balanced Sampler

In [27]:
# BALANCED SAMPLER

train_labels = [
    labels[i]
    for i in train_idx
]

counts = np.bincount(
    train_labels
)

weights = 1.0 / np.sqrt(counts)

sample_weights = [
    weights[t]
    for t in train_labels
]

sampler = WeightedRandomSampler(
    sample_weights,
    len(sample_weights),
    replacement=True
)

print("Class counts:", counts)

Class counts: [4106 2296 3827 6428 6205 5820 5191]


## Cell 10 — Dataloaders

In [28]:
# DATALOADER

train_loader = DataLoader(

    train_ds,

    batch_size=64,

    sampler=sampler,

    num_workers=2,

    pin_memory=True
)

val_loader = DataLoader(

    val_ds,

    batch_size=64,

    shuffle=False,

    num_workers=2,

    pin_memory=True
)

print("Train batches:", len(train_loader))
print("Validation batches:", len(val_loader))

Train batches: 530
Validation batches: 133


## Cell 11 — Models

In [29]:
# MODELS

teacher = timm.create_model(

    "convnext_small",

    pretrained=True,

    num_classes=num_classes

).to(device)

student = timm.create_model(

    "tf_efficientnetv2_s",

    pretrained=True,

    num_classes=num_classes

).to(device)

print("✅ Models Loaded")

✅ Models Loaded


## Cell 12 — Freeze Teacher + EMA

In [30]:
# FREEZE TEACHER

for p in teacher.parameters():

    p.requires_grad = False

teacher.eval()

# EMA

ema = ModelEmaV2(
    student,
    decay=0.999
)

print("✅ Teacher Frozen")
print("✅ EMA Ready")

✅ Teacher Frozen
✅ EMA Ready


## Cell 13 — Feature Projector

In [31]:
# FEATURE PROJECTOR

class FeatureProjector(nn.Module):

    def __init__(
        self,
        in_ch,
        out_ch
    ):

        super().__init__()

        self.block = nn.Sequential(

            nn.Conv2d(
                in_ch,
                512,
                kernel_size=1
            ),

            nn.BatchNorm2d(512),

            nn.GELU(),

            nn.Conv2d(
                512,
                out_ch,
                kernel_size=1
            )
        )

    def forward(self, x):

        return self.block(x)

## Cell 14 — Feature Dimensions

In [32]:
# FEATURE DIMENSIONS

with torch.no_grad():

    dummy_t = torch.randn(
        1,3,224,224
    ).to(device)

    dummy_s = torch.randn(
        1,3,128,128
    ).to(device)

    t_feat = teacher.forward_features(
        dummy_t
    )

    s_feat = student.forward_features(
        dummy_s
    )

t_dim = t_feat.shape[1]
s_dim = s_feat.shape[1]

print("Teacher dim:", t_dim)
print("Student dim:", s_dim)

projector = FeatureProjector(
    s_dim,
    t_dim
).to(device)

Teacher dim: 768
Student dim: 1280


## Cell 15 — Focal Loss

In [33]:
# FOCAL LOSS

class FocalLoss(nn.Module):

    def __init__(
        self,
        gamma=2
    ):

        super().__init__()

        self.gamma = gamma

    def forward(
        self,
        logits,
        targets
    ):

        ce = F.cross_entropy(
            logits,
            targets,
            reduction='none',
            label_smoothing=0.1
        )

        pt = torch.exp(-ce)

        loss = (
            (1 - pt) ** self.gamma
        ) * ce

        return loss.mean()

## Cell 16 — KD Loss

In [34]:
# KD LOSS

class KDLoss(nn.Module):

    def __init__(
        self,
        T=4.0,
        alpha=0.5
    ):

        super().__init__()

        self.T = T
        self.alpha = alpha

        self.ce = FocalLoss()

    def forward(

        self,

        s_logits,
        t_logits,

        labels,

        s_feat,
        t_feat
    ):

        ce_loss = self.ce(
            s_logits,
            labels
        )

        kd_loss = F.kl_div(

            F.log_softmax(
                s_logits / self.T,
                dim=1
            ),

            F.softmax(
                t_logits / self.T,
                dim=1
            ),

            reduction='batchmean'

        ) * (self.T ** 2)

        s_feat = projector(s_feat)

        t_feat = F.adaptive_avg_pool2d(
            t_feat,
            s_feat.shape[-2:]
        )

        feat_loss = (
            1 -
            F.cosine_similarity(
                s_feat.flatten(1),
                t_feat.flatten(1)
            ).mean()
        )

        total = (

            0.4 * ce_loss +

            0.4 * kd_loss +

            0.2 * feat_loss
        )

        return total

loss_fn = KDLoss()

print("✅ KD Loss Ready")

✅ KD Loss Ready


## Cell 17 — Optimizer

In [35]:
# =========================================================
# OPTIMIZER
# =========================================================

optimizer = optim.AdamW(

    list(student.parameters()) +
    list(projector.parameters()),

    lr=2e-4,

    weight_decay=1e-4
)

scheduler = optim.lr_scheduler.CosineAnnealingLR(

    optimizer,

    T_max=30
)

scaler = torch.amp.GradScaler("cuda")

print("✅ Optimizer Ready")

✅ Optimizer Ready


In [36]:
print(train_loader)

## Cell 18 — Training

In [37]:
# TRAINING

best_acc = 0

epochs = 30

print("\n🚀 TRAINING STARTED\n")

for epoch in range(epochs):

    student.train()
    projector.train()

    pbar = tqdm(
        train_loader
    )

    running_loss = 0

    for t_img, s_img, y in pbar:

        t_img = t_img.to(device)
        s_img = s_img.to(device)
        y = y.to(device)

        optimizer.zero_grad()

        with torch.amp.autocast("cuda"):

            with torch.no_grad():

                t_out = teacher(
                    t_img
                )

                t_feat = teacher.forward_features(
                    t_img
                )

            s_out = student(
                s_img
            )

            s_feat = student.forward_features(
                s_img
            )

            loss = loss_fn(

                s_out,
                t_out,

                y,

                s_feat,
                t_feat
            )

        scaler.scale(loss).backward()

        scaler.unscale_(optimizer)

        torch.nn.utils.clip_grad_norm_(
            student.parameters(),
            1.0
        )

        scaler.step(optimizer)

        scaler.update()

        ema.update(student)

        running_loss += loss.item()

        pbar.set_description(

            f"Epoch {epoch+1} "
            f"Loss {loss.item():.4f}"
        )

    scheduler.step()

    # VALIDATION

    ema.module.eval()

    preds = []
    gts = []

    with torch.no_grad():

        for _, s_img, y in val_loader:

            s_img = s_img.to(device)
            y = y.to(device)

            with torch.amp.autocast("cuda"):

                out1 = ema.module(
                    s_img
                )

                out2 = ema.module(
                    torch.flip(
                        s_img,
                        dims=[3]
                    )
                )

                out = (
                    out1 + out2
                ) / 2

            pred = out.argmax(1)

            preds.extend(
                pred.cpu().numpy()
            )

            gts.extend(
                y.cpu().numpy()
            )

    acc = (
        balanced_accuracy_score(
            gts,
            preds
        ) * 100
    )

    print(
        f"\n📊 Epoch {epoch+1}"
    )

    print(
        f"Balanced Accuracy:"
        f" {acc:.2f}%"
    )

    print(
        confusion_matrix(
            gts,
            preds
        )
    )

    # SAVE

    if acc > best_acc:

        best_acc = acc

        torch.save(

            ema.module.state_dict(),

            "best_fer_student.pth"
        )

        print(
            "💾 BEST MODEL SAVED"
        )

print("\n🏁 TRAINING FINISHED")

print(
    f"\n🏆 BEST ACCURACY:"
    f" {best_acc:.2f}%"
)


🚀 TRAINING STARTED



Epoch 1 Loss 0.5097: 100%|██████████| 530/530 [06:34<00:00,  1.34it/s] 



📊 Epoch 1
Balanced Accuracy: 20.53%
[[510 256   1 103  69  61  27]
 [182 201   0  50  49  68  24]
 [461 228   0 115  63  36  54]
 [330 412   0 350 312 121  82]
 [489 457   0 151 283 116  55]
 [552 431   1 125 145 160  41]
 [647 248   0 125  90  84 104]]
💾 BEST MODEL SAVED


Epoch 2 Loss 0.4695: 100%|██████████| 530/530 [05:41<00:00,  1.55it/s]



📊 Epoch 2
Balanced Accuracy: 44.02%
[[ 517  166    9   33  199   91   12]
 [ 128  239    0   17  115   68    7]
 [ 338   99   61   54  187  125   93]
 [  68   89    2  954  394   78   22]
 [ 160   90    0   23 1197   71   10]
 [ 223  188    9   24  523  470   18]
 [ 300   81    9   54  255   68  531]]
💾 BEST MODEL SAVED


Epoch 3 Loss 0.5559: 100%|██████████| 530/530 [05:42<00:00,  1.55it/s]



📊 Epoch 3
Balanced Accuracy: 60.92%
[[ 629  124   18   19  129   80   28]
 [  63  347    3   15   57   71   18]
 [ 208   41  256   27  103  144  178]
 [  31   28    4 1261  208   35   40]
 [ 110   44   10   25 1259   90   13]
 [ 202  103   33   21  326  719   51]
 [  95   52   48   37  131   40  895]]
💾 BEST MODEL SAVED


Epoch 4 Loss 0.4005: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 4
Balanced Accuracy: 66.86%
[[ 673   83   24   22  100   87   38]
 [  70  352    6   12   39   69   26]
 [ 157   27  342   17   73  146  195]
 [  27   21    2 1336  140   31   50]
 [  71   25    7   33 1279  106   30]
 [ 181   66   34   14  216  889   55]
 [  64   22   57   27   67   39 1022]]
💾 BEST MODEL SAVED


Epoch 5 Loss 0.5024: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 5
Balanced Accuracy: 69.13%
[[ 684   75   33   18   89   94   34]
 [  76  350   11    9   35   69   24]
 [ 135   18  413   10   64  150  167]
 [  18   16    4 1365  123   28   53]
 [  61   23   11   31 1276  113   36]
 [ 151   55   44   10  184  961   50]
 [  51   18   76   23   49   44 1037]]
💾 BEST MODEL SAVED


Epoch 6 Loss 0.4456: 100%|██████████| 530/530 [05:43<00:00,  1.54it/s]



📊 Epoch 6
Balanced Accuracy: 70.74%
[[ 702   70   40   15   79   86   35]
 [  75  367   15    8   27   61   21]
 [ 117   13  469    9   53  140  156]
 [  21    9    4 1388  106   29   50]
 [  56   26   16   42 1257  112   42]
 [ 156   44   64   11  155  974   51]
 [  49   19   92   24   43   39 1032]]
💾 BEST MODEL SAVED


Epoch 7 Loss 0.3875: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 7
Balanced Accuracy: 71.30%
[[ 702   65   47   20   66   92   35]
 [  73  373   14   10   28   56   20]
 [ 114   12  488    5   52  129  157]
 [  19    9    5 1404   97   26   47]
 [  50   21   20   45 1258  125   32]
 [ 152   43   69   12  147  987   45]
 [  49   24  103   22   42   40 1018]]
💾 BEST MODEL SAVED


Epoch 8 Loss 0.4473: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 8
Balanced Accuracy: 71.74%
[[ 708   63   47   19   62   96   32]
 [  76  370   16    9   27   57   19]
 [ 103   13  510    8   46  133  144]
 [  14    9    8 1400   93   28   55]
 [  51   22   19   45 1258  120   36]
 [ 153   34   72   12  140  998   46]
 [  45   22  109   22   40   39 1021]]
💾 BEST MODEL SAVED


Epoch 9 Loss 0.3838: 100%|██████████| 530/530 [05:45<00:00,  1.54it/s]



📊 Epoch 9
Balanced Accuracy: 71.95%
[[ 706   61   55   15   53  100   37]
 [  74  376   14    9   24   58   19]
 [ 103   15  515   11   41  130  142]
 [  14    8    6 1403   94   26   56]
 [  47   21   24   44 1252  127   36]
 [ 152   41   80   10  124  999   49]
 [  44   21  110   21   40   38 1024]]
💾 BEST MODEL SAVED


Epoch 10 Loss 0.3499: 100%|██████████| 530/530 [05:45<00:00,  1.53it/s]



📊 Epoch 10
Balanced Accuracy: 71.87%
[[ 694   61   61   16   55  103   37]
 [  69  372   16   11   23   63   20]
 [ 105   12  514   10   40  138  138]
 [  14    8    6 1406   94   25   54]
 [  43   20   23   44 1257  129   35]
 [ 136   41   85   11  121 1014   47]
 [  40   24  114   20   34   44 1022]]


Epoch 11 Loss 0.3447: 100%|██████████| 530/530 [05:45<00:00,  1.53it/s]



📊 Epoch 11
Balanced Accuracy: 72.13%
[[ 689   61   60   18   54  106   39]
 [  71  379   15   10   25   57   17]
 [ 105   12  518    9   40  132  141]
 [  15    9    6 1399   91   30   57]
 [  40   21   23   45 1262  123   37]
 [ 135   44   81   11  115 1026   43]
 [  37   23  118   23   33   42 1022]]
💾 BEST MODEL SAVED


Epoch 12 Loss 0.3736: 100%|██████████| 530/530 [05:43<00:00,  1.54it/s]



📊 Epoch 12
Balanced Accuracy: 71.60%
[[ 682   58   63   18   52  115   39]
 [  79  369   15    7   23   60   21]
 [ 106   11  514   11   41  133  141]
 [  11    8    8 1404   95   27   54]
 [  39   17   23   48 1263  125   36]
 [ 135   40   84   12  129 1009   46]
 [  35   22  117   22   36   45 1021]]


Epoch 13 Loss 0.3759: 100%|██████████| 530/530 [05:45<00:00,  1.53it/s]



📊 Epoch 13
Balanced Accuracy: 71.62%
[[ 680   59   61   18   53  112   44]
 [  80  369   15    8   23   59   20]
 [  99   12  515   12   43  133  143]
 [  10    6    9 1412   96   24   50]
 [  39   15   21   47 1260  135   34]
 [ 131   42   85   12  133 1007   45]
 [  38   21  117   25   34   41 1022]]


Epoch 14 Loss 0.4004: 100%|██████████| 530/530 [05:45<00:00,  1.54it/s]



📊 Epoch 14
Balanced Accuracy: 71.50%
[[ 681   53   62   19   53  112   47]
 [  80  367   18    7   23   57   22]
 [ 100   14  509   12   40  140  142]
 [  11    8   12 1409   95   23   49]
 [  40   16   20   50 1256  134   35]
 [ 135   43   90   12  129  999   47]
 [  40   21  109   20   31   42 1035]]


Epoch 15 Loss 0.2925: 100%|██████████| 530/530 [05:45<00:00,  1.54it/s]



📊 Epoch 15
Balanced Accuracy: 71.38%
[[ 688   49   56   17   52  121   44]
 [  88  363   17    6   22   57   21]
 [ 106   12  511   11   36  136  145]
 [  13    9   11 1406   95   25   48]
 [  41   17   23   52 1251  132   35]
 [ 129   45   96   11  132  991   51]
 [  38   22  110   20   34   39 1035]]


Epoch 16 Loss 0.3169: 100%|██████████| 530/530 [05:46<00:00,  1.53it/s]



📊 Epoch 16
Balanced Accuracy: 71.07%
[[ 681   50   53   17   52  132   42]
 [  88  359   18    7   23   60   19]
 [ 114   12  495   10   37  141  148]
 [  12    8   10 1412   95   22   48]
 [  41   16   22   49 1257  132   34]
 [ 128   45   96   13  134  984   55]
 [  31   22  104   20   34   44 1043]]


Epoch 17 Loss 0.3026: 100%|██████████| 530/530 [05:45<00:00,  1.53it/s]



📊 Epoch 17
Balanced Accuracy: 71.41%
[[ 681   52   58   15   49  131   41]
 [  86  358   17    9   21   63   20]
 [ 103   13  499   11   36  140  155]
 [  15    8   10 1410   92   23   49]
 [  44   15   23   47 1266  126   30]
 [ 128   44   93   12  133  990   55]
 [  32   20   93   18   32   43 1060]]


Epoch 18 Loss 0.3619: 100%|██████████| 530/530 [05:46<00:00,  1.53it/s]



📊 Epoch 18
Balanced Accuracy: 71.24%
[[ 676   52   61   18   45  134   41]
 [  85  359   19    8   25   62   16]
 [ 105   11  501   12   35  143  150]
 [  15    6   10 1405   92   26   53]
 [  40   21   21   48 1258  130   33]
 [ 135   44   90   11  124 1000   51]
 [  34   23   92   17   35   50 1047]]


Epoch 19 Loss 0.2679: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 19
Balanced Accuracy: 70.86%
[[ 675   48   63   18   48  137   38]
 [  91  349   20    5   26   66   17]
 [ 100   12  500   13   36  151  145]
 [  14    9    9 1395   95   30   55]
 [  44   16   23   52 1258  127   31]
 [ 132   41   88   11  126 1011   46]
 [  39   22  103   15   35   48 1036]]


Epoch 20 Loss 0.2878: 100%|██████████| 530/530 [05:45<00:00,  1.54it/s]



📊 Epoch 20
Balanced Accuracy: 70.93%
[[ 679   43   63   17   46  139   40]
 [  93  345   22    5   26   66   17]
 [ 100   10  508   11   38  141  149]
 [  17    6   10 1407   90   30   47]
 [  42   16   24   52 1256  132   29]
 [ 125   46   89    9  129 1006   51]
 [  37   20  105   15   38   51 1032]]


Epoch 21 Loss 0.3641: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 21
Balanced Accuracy: 70.63%
[[ 672   46   66   16   46  138   43]
 [  96  342   21    6   26   64   19]
 [ 100   12  506   11   39  143  146]
 [  16    6   10 1409   91   30   45]
 [  44   17   22   53 1255  132   28]
 [ 116   44   92   11  136 1004   52]
 [  38   18  104   21   41   52 1024]]


Epoch 22 Loss 0.3280: 100%|██████████| 530/530 [05:43<00:00,  1.54it/s]



📊 Epoch 22
Balanced Accuracy: 70.55%
[[ 670   46   62   17   48  144   40]
 [  93  347   18    5   24   67   20]
 [ 101   12  493   13   42  148  148]
 [  16    7   11 1406   91   28   48]
 [  43   19   18   53 1251  138   29]
 [ 119   43   90   10  134 1006   53]
 [  35   21   94   19   40   59 1030]]


Epoch 23 Loss 0.2881: 100%|██████████| 530/530 [05:43<00:00,  1.54it/s]



📊 Epoch 23
Balanced Accuracy: 70.59%
[[ 675   48   60   17   46  140   41]
 [  87  351   18    5   26   64   23]
 [ 100   11  487   13   46  146  154]
 [  15   10    9 1403   89   31   50]
 [  45   21   17   54 1249  135   30]
 [ 121   43   90   10  129 1007   55]
 [  36   22   94   19   40   57 1030]]


Epoch 24 Loss 0.3478: 100%|██████████| 530/530 [05:45<00:00,  1.54it/s]



📊 Epoch 24
Balanced Accuracy: 70.50%
[[ 672   49   62   18   45  137   44]
 [  87  351   19    5   29   56   27]
 [ 102   13  483   13   44  144  158]
 [  15   10    9 1402   91   31   49]
 [  43   21   18   54 1254  134   27]
 [ 127   43   87   12  133  995   58]
 [  36   20   88   20   39   57 1038]]


Epoch 25 Loss 0.3493: 100%|██████████| 530/530 [05:45<00:00,  1.53it/s]



📊 Epoch 25
Balanced Accuracy: 70.50%
[[ 674   50   61   16   44  139   43]
 [  90  350   16    6   30   58   24]
 [  99   13  482   13   41  152  157]
 [  14    8    9 1404   93   31   48]
 [  45   18   19   53 1254  136   26]
 [ 124   45   86   12  135 1000   53]
 [  39   19   92   19   37   59 1033]]


Epoch 26 Loss 0.3649: 100%|██████████| 530/530 [05:46<00:00,  1.53it/s]



📊 Epoch 26
Balanced Accuracy: 70.48%
[[ 675   50   64   17   46  135   40]
 [  88  352   16    6   30   58   24]
 [ 101   13  482   13   41  147  160]
 [  15    6   10 1406   93   30   47]
 [  45   22   20   55 1246  137   26]
 [ 127   44   86   12  139  996   51]
 [  37   19   90   19   39   60 1034]]


Epoch 27 Loss 0.2783: 100%|██████████| 530/530 [05:45<00:00,  1.54it/s]



📊 Epoch 27
Balanced Accuracy: 70.34%
[[ 674   51   68   16   48  130   40]
 [  89  352   16    6   30   57   24]
 [ 104   14  479   12   41  148  159]
 [  14    7   11 1402   93   31   49]
 [  44   22   21   52 1244  142   26]
 [ 123   46   88   12  139  992   55]
 [  38   19   86   20   39   61 1035]]


Epoch 28 Loss 0.2963: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 28
Balanced Accuracy: 70.28%
[[ 679   51   66   16   46  127   42]
 [  88  349   16    6   30   62   23]
 [ 105   13  475   11   41  150  162]
 [  13    8   10 1403   93   30   50]
 [  45   22   19   54 1245  139   27]
 [ 126   43   86   12  140  994   54]
 [  40   20   87   20   41   58 1032]]


Epoch 29 Loss 0.3638: 100%|██████████| 530/530 [05:44<00:00,  1.54it/s]



📊 Epoch 29
Balanced Accuracy: 70.15%
[[ 677   52   65   17   47  126   43]
 [  89  350   16    6   29   61   23]
 [ 105   13  472   11   41  152  163]
 [  15    8   10 1398   91   32   53]
 [  45   19   19   54 1245  142   27]
 [ 123   45   87   12  142  993   53]
 [  42   21   88   20   40   57 1030]]


Epoch 30 Loss 0.2749: 100%|██████████| 530/530 [05:43<00:00,  1.54it/s]



📊 Epoch 30
Balanced Accuracy: 70.08%
[[ 673   53   64   15   49  128   45]
 [  89  348   17    7   29   61   23]
 [ 105   13  470   11   41  155  162]
 [  15    7   10 1396   91   33   55]
 [  46   18   18   54 1247  141   27]
 [ 124   44   83   12  140  997   55]
 [  42   21   87   20   40   56 1032]]

🏁 TRAINING FINISHED

🏆 BEST ACCURACY: 72.13%


## Cell 19 — Load Best Model

In [38]:
# LOAD BEST

student.load_state_dict(

    torch.load(
        "best_fer_student.pth",
        map_location=device
    )
)

student.eval()

print("✅ Best model loaded")

✅ Best model loaded


In [40]:
!pip install onnx onnxscript -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 714.8/714.8 kB 11.3 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.8/166.8 kB 11.0 MB/s eta 0:00:00


## Cell 20 — Export ONNX

In [48]:
# EXPORT ONNX 

import warnings
import os
import torch

#  Hide warnings
warnings.filterwarnings("ignore")
os.environ["PYTHONWARNINGS"] = "ignore"

dummy = torch.randn(
    1,
    3,
    128,
    128
).to(device)

torch.onnx.export(

    student,
    dummy,
    "best_fer_student.onnx",

    export_params=True,

    opset_version=18,  
    do_constant_folding=True,

    input_names=["input"],

    output_names=["output"]
)

print("\n✅ ONNX EXPORTED")

W0529 14:04:01.486000 133 torch/onnx/_internal/exporter/_schemas.py:455] Missing annotation for parameter 'input' from (input, rois, spatial_scale: 'float', pooled_height: 'int', pooled_width: 'int', sampling_ratio: 'int' = -1, aligned: 'bool' = False). Treating as an Input.
W0529 14:04:01.487000 133 torch/onnx/_internal/exporter/_schemas.py:455] Missing annotation for parameter 'rois' from (input, rois, spatial_scale: 'float', pooled_height: 'int', pooled_width: 'int', sampling_ratio: 'int' = -1, aligned: 'bool' = False). Treating as an Input.
W0529 14:04:01.489000 133 torch/onnx/_internal/exporter/_schemas.py:455] Missing annotation for parameter 'input' from (input, boxes, output_size: 'Sequence[int]', spatial_scale: 'float' = 1.0). Treating as an Input.
W0529 14:04:01.491000 133 torch/onnx/_internal/exporter/_schemas.py:455] Missing annotation for parameter 'boxes' from (input, boxes, output_size: 'Sequence[int]', spatial_scale: 'float' = 1.0). Treating as an Input.


[torch.onnx] Obtain model graph for `EfficientNet([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `EfficientNet([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decomposition...
[torch.onnx] Run decomposition... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅

✅ ONNX EXPORTED


In [49]:
import os

print(os.listdir("/kaggle/working"))

['best_fer_student.onnx.data', 'best_fer_student.pth', '.virtual_documents', 'best_fer_student.onnx']
